### ISSUE TITLE
directory existance issues

### ISSUE THREAD

**Issue by mpilosov** [matthew-sochor-zz/transfer#7]
trying to train my first model. using png images and all default settings.
I get the error
``**FileExistsError: [Errno 17] File exists: 'plots'**``
okay... so let's remove that folder.
same error.
Here's the full trace:
```
File "/home/xxx/anaconda3/envs/imclass/bin/transfer", line 11, in <module>
    load_entry_point('transfer==0.36', 'console_scripts', 'transfer')()
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/transfer-0.36-py3.6.egg/transfer/__main__.py", line 123, in main
    project = train_model(project, final = args.final, last = args.last)
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/transfer-0.36-py3.6.egg/transfer/model.py", line 75, in train_model
    os.makedirs(plot_path)
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'plots'
```

This also prints out when it begins to run, but I don't think it's related at all:
```
lib/python3.6/site-packages/h5py-2.7.1-py3.6-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```
though it seems like a reasonable thing to fix.

**Comment by mpilosov** [comment]
okay, after messing with removing and renaming things in the config file (almost all of these were directory issues that should have been caught and handled as exceptions), this is the next error:
```
/home/xxxx/anaconda3/envs/imclass/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/core/ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/imclass/bin/transfer", line 11, in <module>
    load_entry_point('transfer==0.36', 'console_scripts', 'transfer')()
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/transfer-0.36-py3.6.egg/transfer/__main__.py", line 123, in main
    project = train_model(project, final = args.final, last = args.last)
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/transfer-0.36-py3.6.egg/transfer/model.py", line 89, in train_model
    pre_model_files_df = pre_model_files_df[pre_model_files_df.suffix == 'npy']
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/core/ops.py", line 879, in wrapper
    res = na_op(values, other)
  File "/home/xxx/anaconda3/envs/imclass/lib/python3.6/site-packages/pandas-0.22.0-py3.6-linux-x86_64.egg/pandas/core/ops.py", line 818, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```

is this just because of the PNGs? If so, that would have been a helpful thing to mention in the documentation

**Comment by mpilosov** [comment]
converted to jpgs and still no success. I give up, this package shouldn't be this difficult to set up (at least, not according to your README).

**Comment by msochor1** [comment]
I'll give this a look, thanks for the issue

**Comment by msochor1** [comment]
@mpilosov I found the error, it creeped in when I was working on windows compatibility.  I should have a fix up tonight

**Comment by matthew-sochor-zz** [comment]
@mpilosov I think I fixed your issue in https://github.com/matthew-sochor/transfer/commit/804487a22d89c35565c1f2238664313d1335f5d8

I pushed up to version 0.37 on PyPi, please give it another try and let me know if this resolves things for you.  And again, thanks for the issue and I hope this works for you.

**Comment by mpilosov** [comment]
I'm installing from source using `python setup.py install` using a fresh conda environment and would mention that build fails because `flask` isn't in your dependency list. 

having path-completion in the setup would help as well, I did have to constantly check the configure file to ensure everything was entered right (found a typo, fixed it), now it is finally running. I see a lot of `val_categorical_accuracy did not improve` so I'm not sure how well it is going, and am excited to see the end result... 

thanks for the fix! hope this turns into something useful. I'm training it on some synthetic image data that should be very easy for it to learn. starting with a small batch (likely too small) just to make sure the algorithm completes. If I add more images to the directories, simply doing `transfer --run` will pick up where it left off or restart the training?
