### ISSUE TITLE
testing directory issues

### ISSUE THREAD

**Issue by mpilosov** [matthew-sochor-zz/transfer#9]
spent a lot of time replicating this one and trying to work around it, but the prediction only works on individual files.

the models load... which takes a while, and then the same error pops up, trying to access a directory that doesn't exist. because the path is being duplicated: 

here's me trying just a few of many different ways to specify the directory from the command-line... tried being in different directories, to no avail.

(shortened for brevity):

```
inux-x86_64.egg/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'nd_3/nd_3/walk_ ...
```

```
FileNotFoundError: [Errno 2] No such file or directory: 'test/nd_3/test/nd_3/walk_[ ...
```

```
FileNotFoundError: [Errno 2] No such file or directory: 'test/test/nd_3/walk_[
```

**Comment by mpilosov** [comment]
so its something in the way the directory path is being built.

**Comment by matthew-sochor-zz** [comment]
Thanks for finding this, I'm not sure why but my system happily predicts despite this issue...  I'm on mac os, what is your os?

Fixed in https://github.com/matthew-sochor/transfer/commit/7c5c5069a74aa354719ebfca9d100ea5ce2ac319 and I pushed up a new transfer version 0.38.  Please let me know if this fixes the issue.

Thanks again!

**Comment by mpilosov** [comment]
Im on os, too...
but I realize now that I deployed the code to a linux machine running ubuntu 16. I tend to offload computations there and let my mac run cool and quiet.

Thanks for the fix! Will try it out asap.
Did you make the directory checking happen prior to loading the models? Wouldve been easier to diagnose if it werent for the wait.





Not sent from my computer.

On Feb 14, 2018, at 19:04, Matthew A Sochor <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for finding this, I'm not sure why but my system happily predicts despite this issue... I'm on mac os, what is your os?

Fixed in 7c5c506<https://github.com/matthew-sochor/transfer/commit/7c5c5069a74aa354719ebfca9d100ea5ce2ac319> and I pushed up a new transfer version 0.38. Please let me know if this fixes the issue.

Thanks again!

**Comment by matthew-sochor-zz** [comment]
Yeah, I didn't re-order anything, sorry.  The loading time of the model is what it is, that why I made the prediction rest api which loads the model once and sits there ready to make more predictions on demand.

**Comment by mpilosov** [comment]
oh, perfect! 
thank you!!!

**Comment by matthew-sochor-zz** [comment]
@mpilosov can we close this?

**Comment by mpilosov** [comment]
yes. thank you!
Do you mind if I write up a little guide for how to use this software and post it on my blog some time in the near future? (obviously it'll link to the github page).
